### ISSUE TITLE
可以更新一下下一年的日历ics文件吗？

### ISSUE THREAD

**Issue by whzecomjm** [infinet/lunar-calendar#1]
RT，貌似你的ics文件并没有2016年的农历，可以更新一下吗？

**Comment by bearsylla** [comment]
The updated ics is [here](https://github.com/bearsylla/lunar-calendar/blob/master/chinese_lunar_prev_year_next_year.ics) and I have already submitted it as #2

**Comment by whzecomjm** [comment]
@bearsylla thx!

**Comment by bearsylla** [comment]
@whzecomjm 
I have generated new ics.
- 2015 to 2017: https://github.com/bearsylla/lunar-calendar/blob/master/chinese_lunar_2015-01-01_2017-12-31.ics
- 2018 to 2021: https://github.com/bearsylla/lunar-calendar/blob/master/chinese_lunar_2018-01-01_2021-12-31.ics
