### ISSUE TITLE
请问怎么生成带月份的农历格式？

### ISSUE THREAD

**Issue by uclort** [infinet/lunar-calendar#11]
比如九月初一、九月初二这样的。

**Comment by KhienghThenYang** [comment]
> 比如九月初一、九月初二这样的。

文本編輯器打開，比如Windows上可用開源的notepad++，全文正則查找替換就完了。

**Comment by cmddot** [comment]
这个正则表达式好麻烦的。我用的下面这个表达式完成替换的100年的农历日历（工具notepad++）
1. 先将所有 十一月  替换为 冬月，十二月 替换为 腊月。
2.  正则表达式替换（在替换对话框的不要勾选“.匹配新行”）
(閏?[正二三四五六七八九十冬腊]月)([^初十廿三]*?\nEND.+?\n)((BEGIN.+?\nDTSTAMP.+?\nUID.+?\nDTSTART.+?\nDTEND.+?\nSTATUS.+?\nSUMMARY:閏?[正二三四五六七八九十冬腊]月[初十二廿三].+?\nEND.+?\n){0,29}?)(BEGIN.+?\nDTSTAMP.+?\nUID.+?\nDTSTART.+?\nDTEND.+?\nSTATUS.+?\nSUMMARY:)(?=[初十二廿三][^月])

替换为 \1\2\3\5\1

注意：
1. 点击“全部替换”按钮大概30次（什么时候停止替换：在第28次以后的每次点击按钮，注意观察右侧下拉滚动条，如果突然发现，某次替换后行数锐减只剩下200行时，按ctrl+Z回退一次就是全部替换完毕的结果）
2. 因为是从月份名称向后匹配的，日历最开始的几行没有月份名称被匹配，所以只能手动单独处理。

**Comment by uclort** [comment]
@tyc600 感谢你的回复，我之前已经通过修改 py 文件源码达到了效果。
