### ISSUE TITLE
Unable to import ics to Google

### ISSUE THREAD

**Issue by Gnehzis** [infinet/lunar-calendar#19]
Hi Hi,

Was trying to import the ics into google calendar, but both the 3 years and the 10 years ics encountered the same issue.
Please see the screenshot for the error i encountered.

![Import-Error](https://user-images.githubusercontent.com/96817592/147644621-9392e911-4cc2-4d30-be00-715451267601.PNG)

**Comment by hisrule** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by infinet** [comment]
instead of Import, try "From URL"， paste following link:

https://raw.githubusercontent.com/infinet/lunar-calendar/master/chinese_lunar_prev_year_next_year.ics
