### ISSUE TITLE
请更新日历ics文件

### ISSUE THREAD

**Issue by mercurylmy** [infinet/lunar-calendar#3]
请上传1949到2100年间农历ics文件，lunar_ical.py中的URL已经失效了。谢谢。

**Comment by bearsylla** [comment]
我只有 2014-2016 的。
https://github.com/bearsylla/lunar-calendar/blob/master/chinese_lunar_prev_year_next_year.ics

**Comment by bearsylla** [comment]
@mercurylmy 
I have generated new ics.
- 2015 to 2017: https://github.com/bearsylla/lunar-calendar/blob/master/chinese_lunar_2015-01-01_2017-12-31.ics
- 2018 to 2021: https://github.com/bearsylla/lunar-calendar/blob/master/chinese_lunar_2018-01-01_2021-12-31.ics

**Comment by infinet** [comment]
@mercurylmy 1949到2100年的要自己生成。刚试了URL都还有效啊，是不是你的网络有问题。

**Comment by ACsediment** [comment]
上传了一份自己生成的1901-2100的ics，希望能帮到一些人。

https://github.com/ACsediment/GithubWangPan/raw/master/chinese_lunar_1901-01-01_2100-12-31.ics
