### ISSUE TITLE
可不可以做一个只有节气的订阅选项？

### ISSUE THREAD

**Issue by junhaoim** [infinet/lunar-calendar#7]
十分感谢您的这个项目。不过 iCloud 日历现在自带有农历和节假日，所以如果能做一个独立的节气订阅就更好了。

**Comment by fbi007130** [comment]
加一行代码就行了，送给你。
[chinese_lunar_2017-05-01_2021-12-31.ics.zip](https://github.com/infinet/lunar-calendar/files/965874/chinese_lunar_2017-05-01_2021-12-31.ics.zip)

**Comment by infinet** [comment]
https://raw.githubusercontent.com/infinet/lunar-calendar/master/jieqi_tch_2017-01-01_2028-12-31.ics

**Comment by myzcid** [comment]
nice
