### ISSUE TITLE
chinese_lunar_prev_year_next_year.ics runs out soon

### ISSUE THREAD

**Issue by damies13** [infinet/lunar-calendar#8]
chinese_lunar_prev_year_next_year.ics ends 14 days after CNY (1st March 2018)

I would like to make a suggestion: given the name of the ICS file can you set up the python script to run once a year and regenerate the ICS file so that it always has the previous year and next year relative to the current.

**Comment by infinet** [comment]
Run lunar_ical.py without option will do that.
